name: Download Sicalyme_v1.0.2_1650x720px.apk

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  download_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download a file using curl
      run: |
        curl -L -o downloaded_file.zip https://www.mediafire.com/file/ks6cpnh1ypjifp8/sicalyme_v1.0.2_1650x720px.apk/file
        echo "File downloaded successfully!"

    - name: Verify File Exists
      run: ls -l downloaded_file.zip