name: SVG Spec-Perfect Flatten

on:
  push:
    paths:
      - '**.svg'

jobs:
  flatten:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Inkscape
        run: sudo apt-get update && sudo apt-get install -y inkscape

      - name: Flatten SVGs
        run: |
          find . -name "*.svg" -print0 | while IFS= read -r -d '' file; do
            git add "$file"
            inkscape "$file" \
              --export-plain-svg="$file" \
              --actions="select-all;object-to-path;vacuum-defs"
          done

      - name: Commit if changed
        run: |
         git config --global user.name "dujanhung"
         git config --global user.email "chanhung2008.duong@gmail.com"
         git commit -m "Spec-perfect SVG flatten"
         git push